<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Welcome to Blog Module' => 'Добро пожаловать в модуль Блог',
    'A comment has been added and is awaiting validation' => 'Комментарий добавлен и ожидает проверки',
    'Action not found' => 'Действие не найдено',
    'Actions' => 'Действия',
    'Add Sub Catelog' => 'Добавить подкатегорию',
    'Add comments' => 'Добавить комментарий',
    'Are you sure you want to delete this item?' => 'Точно удалить?',
    'Author' => 'Автор',
    'Banner' => 'Баннер',
    'Blog' => 'Статьи',
    'Blog Category' => 'Категория блога',
    'Blog Categorys' => 'Категории блога',
    'Blog Comment' => 'Комментарий блога',
    'Blog Comments' => 'Комментарии блога',
    'Blog Post' => 'Запись блога',
    'Blog Posts' => 'Записи блога',
    'Blog Tag' => 'Тег блога',
    'Blog Tags' => 'Теги блога',
    'Brief' => 'Краткий Анонс',
    'CONSTANT_NO' => 'НЕТ',
    'CONSTANT_YES' => 'ДА',
    'Category' => 'Категория',
    'Category ID' => 'ID Категории',
    'Click' => 'Просмотры',
    'Comments' => 'Комментарии',
    'Comments Count' => 'Кол-во комментариев',
    'Confirm' => 'Подтвердить',
    'Content' => 'Текст',
    'Create' => 'Создать',
    'Create ' => 'Создать ',
    'Create Time' => 'Время создания',
    'Created At' => 'Создано',
    'Delete' => 'Удалить',
    'Email' => 'Email',
    'Frequency' => 'Частота',
    'ID' => 'ID',
    'Is Nav' => 'Навигация',
    'Math, for example, 45-12 = 33' => 'Напишите решение, например, 45-12 = 33',
    'NO' => 'Нет',
    'Name' => 'Имя',
    'PAGE_TYPE_LIST' => 'PAGE_TYPE_LIST',
    'PAGE_TYPE_PAGE' => 'PAGE_TYPE_PAGE',
    'PROMPT_STATUS' => 'Все',
    'Page Size' => 'Размер страницы',
    'Parent ID' => 'ID родителя',
    'Please Filter' => 'Фильтр',
    'Post ID' => 'ID Записи',
    'Redirect Url' => 'URL перенаправления',
    'Reset' => 'Сбросить',
    'Root Category' => 'Корневая категория',
    'STATUS_ACTIVE' => 'Актив',
    'STATUS_DELETED' => 'Удалено',
    'STATUS_INACTIVE' => 'Неактив',
    'Search' => 'Поиск',
    'Send' => 'Отправить',
    'Slug' => 'Транслит',
    'Sort Order' => 'Сортировка',
    'Status' => 'Статус',
    'Successfully confirm' => 'Успешно подтверждено',
    'Successfully delete' => 'Успешно удалено',
    'Tags' => 'Теги',
    'Template' => 'Шаблон',
    'Title' => 'Название',
    'Update' => 'Изменить',
    'Update ' => 'Изменить ',
    'Updated At' => 'Обновлено',
    'Url' => 'Url',
    'User ID' => 'User ID',
    'Verify code' => 'Проверочный код',
    'View' => 'Просмотреть',
    'Write comments' => 'Написать комментарий',
    'YES' => 'Да',
];
