<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Please Select' => '请选择',
	'Access denied.' => '拒绝访问',
	'Add' => '添加',
	'Cancel' => '取消',
	'Create' => '创建',
	'Delete' => '删除',
	'Edit' => '编辑',
	'Remove' => '移除',
	'Save' => '储存',
	'View' => '查看',

	'STATUS_ACTIVE' => '正常',
	'STATUS_INACTIVE' => '禁用',
	'STATUS_DELETED' => '删除',

	'CONSTANT_YES' => '是',
	'CONSTANT_NO' => '否',

	'PAGE_TYPE_LIST' => '列表页',
	'PAGE_TYPE_PAGE' => '单页面',

	'Root Catalog' => '顶级目录',

	'Home' => '首页',

);

