<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Welcome to Blog Module' => 'Bem-vindo ao módulo blog',
    'A comment has been added and is awaiting validation' => 'Um comentário foi adicionado e aguarda validação',
    'Action not found' => 'Ação não encontrada',
    'Actions' => 'Ações',
    'Add Sub Catelog' => 'Adicionar Sub Catálogo',
    'Add comments' => 'Adicionar Comentários',
    'Are you sure you want to delete this item?' => 'Tem certeza de que deseja excluir este item?',
    'Author' => 'Autor',
    'Banner' => 'Banner',
    'Blog' => 'Blog',
    'Blog Category' => 'Categoria do blog',
    'Blog Categorys' => 'Categorias de blog',
    'Blog Comment' => 'Comentário do blog',
    'Blog Comments' => 'Comentários do blog',
    'Blog Post' => 'Postagem do blog',
    'Blog Posts' => 'Postagens do blog',
    'Blog Tag' => 'Tag',
    'Blog Tags' => 'Tags',
    'Brief' => 'Resumo',
    'CONSTANT_NO' => 'CONSTANT_NO',
    'CONSTANT_YES' => 'CONSTANT_YES',
    'Category' => 'Categoria',
    'Category ID' => 'ID da categoria',
    'Click' => 'Clique',
    'Comments' => 'Comentários',
    'Comments Count' => 'Contagem de comentários',
    'Confirm' => 'Confirmar',
    'Content' => 'Conteúdo',
    'Create' => 'Criar',
    'Create ' => 'Criar ',
    'Create Time' => 'Hora de criação',
    'Created At' => 'Criado em',
    'Delete' => 'Excluir',
    'Email' => 'Email',
    'Frequency' => 'Frequência',
    'ID' => 'ID',
    'Is Nav' => 'Navegação',
    'Math, for example, 45-12 = 33' => 'Matemática, por exemplo, 45-12 = 33',
    'NO' => 'NÃO',
    'Name' => 'Nome',
    'PAGE_TYPE_LIST' => 'PAGE_TYPE_LIST',
    'PAGE_TYPE_PAGE' => 'PAGE_TYPE_PAGE',
    'PROMPT_STATUS' => 'PROMPT_STATUS',
    'Page Size' => 'Tamanho da página',
    'Parent ID' => 'ID Pai',
    'Please Filter' => 'Filtrar',
    'Post ID' => 'ID da Postagem',
    'Redirect Url' => 'URL de redirecionamento',
    'Reset' => 'Resetar',
    'Root Category' => 'Categoria raiz',
    'STATUS_ACTIVE' => 'STATUS_ACTIVE',
    'STATUS_DELETED' => 'STATUS_DELETED',
    'STATUS_INACTIVE' => 'STATUS_INACTIVE',
    'Search' => 'Pesquisa',
    'Send' => 'Enviar',
    'Slug' => 'Slug',
    'Sort Order' => 'Classificação',
    'Status' => 'Status',
    'Successfully confirm' => 'Confirmado com sucesso',
    'Successfully delete' => 'Excluído com sucesso',
    'Tags' => 'Tags',
    'Template' => 'Modelo',
    'Title' => 'Título',
    'Update' => 'Alterar',
    'Update ' => 'Alterar ',
    'Updated At' => 'Alterado em',
    'Url' => 'Url',
    'User ID' => 'ID do usuário',
    'Verify code' => 'Verificar código',
    'View' => 'Ver',
    'Write comments' => 'Escrever comentárioй',
    'YES' => 'SIM',
];
